<?php

use App\Users;
use Illuminate\Database\Seeder;
use App\User;

class UserTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'id' => 1,
                'name' => 'admin',
                'displayname' => 'admin admin',
                'email' => 'admin@admin.com',
                'group' => '1',
                'gender' => NULL,
                'age' => '24',
                'profile_pic' => '1531736803.jpg',
                'password' => '$2y$12$MPT5bSAa1XXlom7LcAIVFuatFIW9MG/LmxUwDZuB/WFaEF3.nGANW',
                'verified' => 1,
                'role_id' => 1,
                'species_id' => 2,
                'is_online' => 0,
                'last_activity' => '2019-10-09 01:10:03',
                'securitypin' => 1234,
                'remember_token' => 'xlk4I1jjQIAXKknO9sbLYvhGquXv9aAgr8gNJFwtU4KFQ6qmQNXqhsevyB4n',
                'created_at' => '2018-06-12 05:30:00',
                'updated_at' => '2019-10-09 01:10:03',
                'stripe_id' => 'cus_DA6jnV4lIr0IFo',
                'card_brand' => 'Visa',
                'card_last_four' => '1111',
                'is_deleted' => 'false',
                'trial_ends_at' => NULL,
                'about_me' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod

tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,

quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo

consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse

cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non

proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'suspend' => 0,
                'ticketit_admin' => 1,
                'ticketit_agent' => 1,
                'myfuns' => '["1","2","3","4","5"]',
                'is_notifications_enable' => 1,
                'is_private' => 0,
                'otp' => '111111',
                'uuid' => '111111',
                'sl_username' => 'testing',
            ],
            [
                'id' => 2,
                'name' => 'Sun God Of Love & Light',
                'displayname' => 'User1',
                'email' => 'user@admin.com',
                'group' => '1',
                'gender' => '1',
                'age' => '13',
                'profile_pic' => '1569402375.jpg',
                'password' => '$2y$12$MPT5bSAa1XXlom7LcAIVFuatFIW9MG/LmxUwDZuB/WFaEF3.nGANW',
                'verified' => 1,
                'role_id' => 4,
                'species_id' => 2,
                'is_online' => 1,
                'last_activity' => '2019-10-09 05:07:48',
                'securitypin' => 2342,
                'remember_token' => 'WacJLNSgxRpOZ3vbpMxjR6px1ADBU5GEkUvX6dVxOAubqoOje1lplXsGWhbs',
                'created_at' => '2018-06-26 13:25:12',
                'updated_at' => '2019-10-09 05:07:48',
                'stripe_id' => 'cus_D9f6ccBoUEoA5h',
                'card_brand' => 'Visa',
                'card_last_four' => '1111',
                'is_deleted' => 'false',
                'trial_ends_at' => NULL,
                'about_me' => 'i am best person in the world :)',
                'suspend' => 0,
                'ticketit_admin' => 0,
                'ticketit_agent' => 1,
                'myfuns' => '["2","3","4"]',
                'is_notifications_enable' => 1,
                'is_private' => 0,
                'otp' => '123456',
                'uuid' => '111111',
                'sl_username' => 'testing',
            ],
            [
                'id' => 691,
                'name' => 'Mikekey.Monday',
                'displayname' => 'Monday Madness',
                'email' => 'Mikekey.Monday@lsl.com',
                'group' => '2',
                'gender' => '1',
                'age' => '33',
                'profile_pic' => 'screen-shot-2019-09-19-at-124804-am-d6b63.png',
                'password' => '$2y$10$RTbQPMHHZcQ.DtVXxKrbReRkQWHTyGFasFFti9.wVgcTAfIdV3jH6',
                'verified' => 1,
                'role_id' => 4,
                'species_id' => 1,
                'is_online' => 0,
                'last_activity' => '2019-10-01 08:26:49',
                'securitypin' => NULL,
                'remember_token' => 'fm4fuVFQ7UAhzPIlmbLlHJsOwhaFvcY1eDxWrzgLpw6y5v8XQq0TnjnCRYzP',
                'created_at' => '2019-10-01 13:20:15',
                'updated_at' => '2019-10-02 14:19:29',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'is_deleted' => 'false',
                'trial_ends_at' => NULL,
                'about_me' => 'I don\'t have much to say about myself more than I am a humble person that is trying my 100% to be honest everyday. I love people and if people love me I love them even more. So live life and do whatever',
                'suspend' => 0,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'myfuns' => '["1","2","4"]',
                'is_notifications_enable' => 1,
                'is_private' => 0,
                'otp' => NULL,
                'uuid' => '52b0b15a-571f-4d4f-94a5-4e4ea22f2c1d',
                'sl_username' => 'Mikekey.Monday',
            ],
            [
                'id' => 692,
                'name' => 'testing',
                'displayname' => 'hey baby',
                'email' => 'hhhh@hhhh.com',
                'group' => '2',
                'gender' => '1',
                'age' => '25',
                'profile_pic' => 'default.png',
                'password' => '$2y$10$oZd/0CYlnmwxYiyMnmyit.KMIVPCfb22UqENcXfCQZAC2PzRATL5e',
                'verified' => 1,
                'role_id' => 3,
                'species_id' => 1,
                'is_online' => 0,
                'last_activity' => '2019-10-02 11:40:30',
                'securitypin' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-02 17:09:19',
                'updated_at' => '2019-10-02 17:10:30',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'is_deleted' => 'false',
                'trial_ends_at' => NULL,
                'about_me' => 'hello there',
                'suspend' => 0,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'myfuns' => NULL,
                'is_notifications_enable' => 1,
                'is_private' => 0,
                'otp' => NULL,
                'uuid' => NULL,
                'sl_username' => NULL,
            ],
            [
                'id' => 693,
                'name' => 'testing2',
                'displayname' => 'rahul test',
                'email' => 'sahil9256@gmail.com',
                'group' => '1',
                'gender' => '1',
                'age' => '20',
                'profile_pic' => 'default.png',
                'password' => '$2y$10$E.98O909bI/J4hJrAPDOPevYCh1AUyLZJXiIDmVDy8/f0j/W9S1aW',
                'verified' => 1,
                'role_id' => 3,
                'species_id' => 1,
                'is_online' => 0,
                'last_activity' => '2018-07-17 07:16:27',
                'securitypin' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-03 12:25:59',
                'updated_at' => '2019-10-03 12:25:59',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'is_deleted' => 'false',
                'trial_ends_at' => NULL,
                'about_me' => 'testing',
                'suspend' => 0,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'myfuns' => NULL,
                'is_notifications_enable' => 1,
                'is_private' => 0,
                'otp' => NULL,
                'uuid' => NULL,
                'sl_username' => NULL,
            ]
        ];
        foreach($users as $row){
            if(count(User::where('email', $row['email'])->get()) <= 0){
                User::create($row);
            }
        }
    }
}
